---
# tasks file for authconfig
#- set_fact:
#    distro: "{{ansible_lsb.id}}-{{ansible_lsb.major_release}}"
#  when: ansible_lsb.description is defined
#  tags:
#    - aad_adjoin
#    - aad_sssd
- set_fact:
    distro: "{{ansible_os_family}}-{{ansible_distribution_major_version}}"
  tags:
    - aad_adjoin
    - aad_sssd

# - set_fact:
#    distro: "{{ansible_lsb.id}}-{{ansible_lsb.major_release}}"
#  when: ansible_lsb.description is defined
#  tags:
#    - aad_adjoin
#    - aad_sssd
#- set_fact:
#    distro: "{{ansible_distribution}}-{{ansible_distribution_major_version}}"
#  when: ansible_lsb.description is undefined
#  tags:
#    - aad_adjoin
#    - aad_sssd

# load version-specific variables
- block:
    - include_vars: "{{ item }}"
      with_first_found:
        - "../vars/{{distro}}.yml"
  rescue:
    - fail: msg="Variables file for distro {{ distro }} were not found."
  tags:
    - aad_adjoin
    - aad_sssd    

- include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

# Common files between the dists
- name: krb5.conf
  template:
    src: krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
  tags:
    - aad_krb5_conf
    - aad_sssd

- name: sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: restart sssd
  tags:
    - aad_sssd_conf
    - aad_sssd

#- name: access.conf
#  template:
#    src: access.conf.j2
#    dest: /etc/security/access.conf
#    owner: root
#    group: root
#    mode: 0640

- name: Install ssh legal thing
  copy:
    src: ssh_issue
    dest: /etc/ssh/issue
    owner: root
    group: root
    mode: 0644
  notify:
    - restart ssh
  tags:
    - aad_ssh
    - aad_sssd

- name: Update sshd_config for legal thing
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'Banner /etc/ssh/issue'
    regexp: '^(#|)Banner\ .*'
  notify:
    - restart ssh
  tags:
    - aad_ssh
    - aad_sssd

- name: Update sshd_config to allow PasswordAuthentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication yes'
    regexp: '^(#|)PasswordAuthentication\ .*'
  notify:
    - restart ssh
  tags:
    - aad_ssh
    - aad_sssd

- name: Update sshd_config to remove old PasswordAuthentication no if exists
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'
    state: absent
  notify:
    - restart ssh
  tags:
    - aad_ssh
    - aad_sssd

- meta: flush_handlers

#- name: enable and start sssd
#  service:
#    name: sssd
#    enabled: yes
#    state: restarted

#- name: enable and start oddjob
#  service:
#    name: oddjobd
#    enabled: yes
#    state: started
#  notify: authconfig mkhomedir

# JB: Not sure if we need this with Kerb Auth
#- name: allow password auth
#  lineinfile:
#    dest: /etc/ssh/sshd_config
#    line: 'PasswordAuthentication yes'
#    regexp: '^(#|)PasswordAuthentication\ .*'
#  notify: restart ssh

#- include: test.yml
