---
# handlers file for authconfig

# --enablemkhomedir only seems to work if --savebackup isn't specified so it was moved to a handler
# invoked after oddjob is started.
- name: authconfig mkhomedir
  command: "/usr/sbin/authconfig --enablemkhomedir --update"
#  args:
#    creates: /var/lib/authconfig/backup-ansible_configured2
  notify: restart sssd

- name: disable nslcd
  service:
    name: nslcd
    enabled: false
    state: stopped
  ignore_errors: false
  failed_when: false

- name: clear nscd
  shell: "/usr/sbin/nscd -i passwd; /usr/sbin/nscd -i group"
  ignore_errors: yes

- name: clear ssh AllowGroups
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(AllowGroups .*)'
    line:   '# \1'
    backrefs: yes
    state: present
  notify: restart ssh

- name: restart sssd
  service:
    name: sssd
    enabled: yes
    state: restarted

- name: restart dbus
  service:
    name: messagebus
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Amazon' or ansible_os_family == 'RedHat'

- name: restart dbus
  service:
    name: dbus
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'

- name: restart systemd-logind
  service:
    name: systemd-logind
    enabled: yes
    state: restarted
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: restart oddjob
  service:
    name: oddjobd
    enabled: yes
    state: restarted

- name: restart ssh
  service:
    name: sshd
    enabled: yes
    state: restarted
  when: ansible_os_family == 'RedHat' or ansible_distribution == 'Amazon'

- name: restart ssh
  service:
    name: ssh
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'

- name: pam-auth-update
  command: /usr/sbin/pam-auth-update --package
