---
# handlers file for authconfig

# --enablemkhomedir only seems to work if --savebackup isn't specified so it was moved to a handler
# invoked after oddjob is started.
- name: authconfig mkhomedir
  command: "/usr/sbin/authconfig --enablemkhomedir --update"
#  args:
#    creates: /var/lib/authconfig/backup-ansible_configured2
  notify: restart sssd

- name: disable nslcd
  service:
    name: nslcd
    enabled: false
    state: stopped
  ignore_errors: false
  failed_when: false

- name: clear nscd
  shell: "/usr/sbin/nscd -i passwd; /usr/sbin/nscd -i group"
  ignore_errors: yes

- name: clear ssh AllowGroups
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^(AllowGroups .*)'
    line:   '# \1'
    backrefs: yes
    state: present
  notify: 
    - restart ssh
    - restart sshd

- name: restart sssd
  service:
    name: sssd
    enabled: yes
    state: restarted

# messagebus for Cent/RedHat/Amazon
- name: restart messagebus
  service:
    name: messagebus
    enabled: yes
    state: restarted
  when: distro == 'RedHat-6' || distro == 'RedHat-5'

# Service is dbus for Cent/RedHat 7
- name: restart dbus
  service:
    name: dbus
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu' or distro == 'RedHat-7'


- name: restart oddjob
  service:
    name: oddjobd
    enabled: yes
    state: restarted

- name: restart sshd
  service:
    name: sshd
    enabled: yes
    state: restarted
  when: ansible_os_family == 'RedHat'

- name: restart logind
  service: 
    name: systemd-logind
    enabled: yes
    state: restarted
  when: distro == 'RedHat-7'

- name: restart ssh
  service:
    name: ssh
    enabled: yes
    state: restarted
  when: ansible_distribution == 'Ubuntu'

- name: pam-auth-update
  command: /usr/sbin/pam-auth-update --package
